//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotifyApp.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpotifyApp.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBUM.
        /// </summary>
        public static string AlbumTypeAlbum {
            get {
                return ResourceManager.GetString("AlbumTypeAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPILATION.
        /// </summary>
        public static string AlbumTypeCompilation {
            get {
                return ResourceManager.GetString("AlbumTypeCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINGLE.
        /// </summary>
        public static string AlbumTypeSingle {
            get {
                return ResourceManager.GetString("AlbumTypeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string ItemTypeAlbum {
            get {
                return ResourceManager.GetString("ItemTypeAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ItemTypeArtist {
            get {
                return ResourceManager.GetString("ItemTypeArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Features.
        /// </summary>
        public static string ItemTypeAudioFeatures {
            get {
                return ResourceManager.GetString("ItemTypeAudioFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string ItemTypeGenre {
            get {
                return ResourceManager.GetString("ItemTypeGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string ItemTypePlaylist {
            get {
                return ResourceManager.GetString("ItemTypePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string ItemTypeTrack {
            get {
                return ResourceManager.GetString("ItemTypeTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string ItemTypeUser {
            get {
                return ResourceManager.GetString("ItemTypeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked songs.
        /// </summary>
        public static string LikedSongs {
            get {
                return ResourceManager.GetString("LikedSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string MenuLogOut {
            get {
                return ResourceManager.GetString("MenuLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist.
        /// </summary>
        public static string MenuNewPlaylist {
            get {
                return ResourceManager.GetString("MenuNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist Folder.
        /// </summary>
        public static string MenuNewPlaylistFolder {
            get {
                return ResourceManager.GetString("MenuNewPlaylistFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Session.
        /// </summary>
        public static string MenuPrivateSession {
            get {
                return ResourceManager.GetString("MenuPrivateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavigationHome {
            get {
                return ResourceManager.GetString("NavigationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string NavigationSearch {
            get {
                return ResourceManager.GetString("NavigationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only visible to you.
        /// </summary>
        public static string OnlyVisibleToYou {
            get {
                return ResourceManager.GetString("OnlyVisibleToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PlayerNext {
            get {
                return ResourceManager.GetString("PlayerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayerPlay {
            get {
                return ResourceManager.GetString("PlayerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PlayerPrevious {
            get {
                return ResourceManager.GetString("PlayerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string PlayerShuffle {
            get {
                return ResourceManager.GetString("PlayerShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top artists this month.
        /// </summary>
        public static string TopArtistsThisMonth {
            get {
                return ResourceManager.GetString("TopArtistsThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top tracks this month.
        /// </summary>
        public static string TopTracksThisMonth {
            get {
                return ResourceManager.GetString("TopTracksThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALBUM.
        /// </summary>
        public static string TrackGridHeaderAlbum {
            get {
                return ResourceManager.GetString("TrackGridHeaderAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION.
        /// </summary>
        public static string TrackGridHeaderDuration {
            get {
                return ResourceManager.GetString("TrackGridHeaderDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        public static string TrackGridHeaderTitle {
            get {
                return ResourceManager.GetString("TrackGridHeaderTitle", resourceCulture);
            }
        }
    }
}
